apiVersion: v1
kind: Service
metadata:
  name: postgresql-mlflow-service
spec:
  ports:
    - name: postgresql-port
      port: 5432
      targetPort: 5432
    - name: custom-port
      port: 5555
      targetPort: 5555
  selector:
    app: postgresql-mlflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-mlflow
  template:
    metadata:
      labels:
        app: postgresql-mlflow
    spec:
      containers:
        - image: postgres:14.0
          name: postgres
          env:
            - name: POSTGRES_USER
              value: mlflow
            - name: POSTGRES_PASSWORD
              value: mlflow
            - name: POSTGRES_DB
              value: mlflow
          ports:
            - containerPort: 5432
              name: postgre
            - containerPort: 5555
              name: custom-port
          volumeMounts:
            - name: postgresql-volume
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: postgresql-volume
          persistentVolumeClaim:
            claimName: postgresql-mlflow-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-mlflow-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi