apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: mlflow-server-service2
spec:
  selector:
    app.kubernetes.io/name: mlflow-server2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
