apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-ingress-listener-8082
  namespace: emissary
spec:
  port: 8082
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL